// FRD §9.5.2 v1.3 — LOI (Letter of Intent / 투자 의향서)
//
// Backs FR-R-005 (LOI generation, signing, status workflow). Generated by
// FR-R-003 (RE100) or FR-R-004 (retail). Tracked by FR-R-006 (portfolio
// dashboard) and managed by operators at /admin/loi.

import { z } from 'zod';

import { BUILDING_ID_REGEX } from './building.js';

export const LOIStatus = z.enum([
  'draft',
  'submitted',
  'under_review',
  'approved',
  'rejected',
  'contract',
]);
export type LOIStatus = z.infer<typeof LOIStatus>;

const LOITerms = z.object({
  /** Investment horizon in years (1–30 typical). */
  years: z.number().int().min(1).max(30),
  /** Equity ratio of capex (0–100). */
  equity_ratio_pct: z.number().min(0).max(100),
  /** Investor's expected yield from the simulator at submission time. */
  expected_yield_pct: z.number().min(0).max(15),
});
export type LOITerms = z.infer<typeof LOITerms>;

export const LOI = z.object({
  id: z.string().min(1),
  investor_id: z.string().min(1),
  /** Buildings the investor is targeting (FR-R-002 carrier). At least one. */
  sites: z.array(z.string().regex(BUILDING_ID_REGEX)).min(1),
  capex_won: z.number().int().nonnegative(),
  terms: LOITerms,
  status: LOIStatus,
  /** PDF generated by FR-R-005 generator. Null while draft. */
  pdf_url: z.string().url().nullable(),
  /** SHA-256 of the signed PDF, recorded on Hyperledger Fabric (FR-S-007). */
  blockchain_hash: z.string().regex(/^[0-9a-f]{64}$/).nullable(),
  /** Mock SMS-signature timestamp. Null until signing completes. */
  signed_at: z.string().datetime().nullable(),
  /** Disclaimer text shown to retail investors (비구속력 명시). */
  is_non_binding: z.boolean().default(false),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});
export type LOI = z.infer<typeof LOI>;

// ---------------------------------------------------------------------------
// Status transitions allowed by FR-R-005 §6 workflow
// ---------------------------------------------------------------------------

const ALLOWED_TRANSITIONS: Record<LOIStatus, readonly LOIStatus[]> = {
  draft:        ['submitted'],
  submitted:    ['under_review'],
  under_review: ['approved', 'rejected'],
  approved:     ['contract'],
  rejected:     [],
  contract:     [],
} as const;

export function canTransition(from: LOIStatus, to: LOIStatus): boolean {
  return ALLOWED_TRANSITIONS[from].includes(to);
}
